### ISSUE TITLE
Pretrained weights for fine-tune VLMs?

### ISSUE THREAD

**Issue by ghost** [yuhui-zh15/VLMClassifier#1]
Dear Yuhui Zhang,

Thank you for your great effort! I found your paper very interesting and informative.

Could you provide us with the pretrained weights for fine-tuned VLMs? It would be a tremendous help for me to continue my research.

Best,
Tin

**Comment by Weibin44** [comment]
Hi Tin, did you find the code for fine-tuning LlaVA? It seems there are only for clip under train_analysis folder. Thanks for your help!

**Comment by ghost** [comment]
Hi @Weibin44 , that's what I am asking for

**Comment by yuhui-zh15** [comment]
Thanks for your interest in our work!

We simply use the official repo to fine-tune LLaVA and BLIP2.

We will finish cleaning these fine-tuning codes and releasing model weights in the next month.

**Comment by yuhui-zh15** [comment]
Hi all, we have cleaned the training codes and released the model weights. Please see the updated README, thanks!
