### ISSUE TITLE
process script for imagenet.jsonl

### ISSUE THREAD

**Issue by ForJadeForest** [yuhui-zh15/VLMClassifier#3]
I want to train LLaVA in imagenet dataset, but I find the file `imagnet.jsonl` do not exist in `./data`, maybe it's too large for git. 

Can you please upload the process file to generate `imagenet.jsonl`?

**Comment by yuhui-zh15** [comment]
Hi @ForJadeForest, I've uploaded here https://drive.google.com/drive/folders/1R789VmU4ph-Cyi4Q4qCFKG6LQlHx0kTR
