### ISSUE TITLE
Probabilistic inference for VLMs

### ISSUE THREAD

**Issue by akskuchi** [yuhui-zh15/VLMClassifier#4]
Hello,

Thanks a lot for your nice work!

I have a question regarding using probabilistic inference for VLMs. Section `3.1` and supplementary `B.3` in the [paper](https://arxiv.org/pdf/2405.18415) mention that computing probabilities for each of the classes is computationally expensive.

Could you please explain why this is the case? 
For a given `<image, prompt>` input, wouldn't the probability distribution over entire VLM vocabulary (including all the class labels), be available at once, in one forward pass?

Kind regards.

**Comment by yuhui-zh15** [comment]
Hi @akskuchi, thank you for your question. Each class label is not a single token, instead they have multiple tokens. So we need to do one pass for each label. You can refer to the code for more details:

https://github.com/yuhui-zh15/VLMClassifier/blob/2d3fbf6f7f410a6e39d567a4c507058a9ac4fb5b/inference_analysis/main.py#L25
